env:
  global:
    - CC_TEST_REPORTER_ID=0317e203635c4363d1d95fa7c92383dbd06180c1d9ccdfe899f2af76d67f649d
language: python
python:
- 3.8
before_install:
- pip install poetry
install:
- poetry install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- make lint
- make test
fter_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
