# Generated by Django 3.1.7 on 2021-04-07 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0002_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
