# Generated by Django 3.1.7 on 2021-04-09 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_auto_20210407_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_name',
            new_name='status',
        ),
    ]
