# Generated by Django 3.1.7 on 2021-04-07 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuces', '0003_auto_20210407_1821'),
        ('tasks', '0002_remove_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statuces.status'),
        ),
    ]
