# Generated by Django 3.1.7 on 2021-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0007_auto_20210413_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, null=True, related_name='Labels', to='labels.Label'),
        ),
    ]
