# Generated by Django 3.1.7 on 2021-04-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0005_auto_20210420_1906'),
        ('tasks', '0010_auto_20210420_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statuses.status'),
        ),
    ]
