name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version  : 3.8
      - name: Install dependencies      
        run: |
          pip install poetry
          make install
      - name: Run a linter
        run: |
          make lint
      - name: Run tests
        env:
          SECRET_KEY: "*e_&13n42vkj9@m99@*(nsg8i-2&77h)n3jn1v9f@1c=1utsx%"
        run: |
          make test
      - name: Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 0317e203635c4363d1d95fa7c92383dbd06180c1d9ccdfe899f2af76d67f649d
        with:
          coverageCommand: make test
          debug: true
